### ISSUE TITLE
Add the purepreseller procedure

### ISSUE THREAD

**Issue by Ajithkumarsri** [AjithkumarMadurainz/Gitnewtrining#3]
Need to add the pure  pre seller mobile data adding procedure
[Auto stock -Mobile order.txt](https://github.com/AjithkumarMadurainz/Gitnewtrining/files/10319570/Auto.stock.-Mobile.order.txt)

**Comment by AjithkumarMadurainz** [comment]
Thanks for the request the new feature add in that file

**Comment by AjithkumarMadurainz** [comment]
Hi Ajithkumarsri we have resolved the you requested issue
